<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.fyr</string>
    <key>name</key>
    <string>Fyr</string>
    <key>comment</key>
    <string>Fyr language</string>
    <key>fileTypes</key>
    <array>
      <string>fyr</string>
    </array>
    <key>foldingStartMarker</key>
    <string>({|\()\s*$</string>
    <key>foldingStopMarker</key>
    <string>(}|\))\s*$</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>Block comments</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.fyr</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block.fyr</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Line comments</string>
        <key>begin</key>
        <string>//</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.fyr</string>
          </dict>
        </dict>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>comment.line.double-slash.fyr</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Interpreted string literals</string>
        <key>begin</key>
        <string>("""|")</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.fyr</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.fyr</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.fyr</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string_escaped_char</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_placeholder</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Syntax error using slices</string>
        <key>match</key>
        <string>\[\](\s+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.slice.fyr</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Syntax error numeric literals</string>
        <key>match</key>
        <string>\b0[0-7]*[89]\d*\b</string>
        <key>name</key>
        <string>invalid.illegal.numeric.fyr</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Loops</string>
        <key>match</key>
        <string>(for)\s*\((([^\)]+|\([^\)]*\))*)\)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.fyr</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>comment</key>
                <string>for (let|var..in..)</string>
                <key>match</key>
                <string>(let|var) ([\w\s,]+) (in) (.*)</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.data.fyr</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#variables</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.fyr</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>$self</string>
                      </dict>
                    </array>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>comment</key>
                <string>others</string>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Function declarations</string>
        <key>match</key>
        <string>^([a-z\s]+)?\s*(\bfunc\b)(?:\s*(const\s?)?(?:(\w+)\.)?([a-zA-Z_]\w*)(?:&lt;(\w+)\s+(is)\s+([\w\s\|]+)&gt;)?(?=\())?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(export|async|\s)*</string>
                <key>name</key>
                <string>keyword.meta.fyr</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.meta.function.fyr</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.data.fyr</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.fyr</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.fyr</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.fyr</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>keyword.meta.fyr</string>
          </dict>
          <key>8</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage_types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#custom_type</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>min/max/sizeof</string>
        <key>match</key>
        <string>(min|max|sizeof|alignedSizeof)&lt;([a-zA-Z_]\w*)&gt;[^\(]</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.builtin.fyr</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage_types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#custom_type</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Functions</string>
        <key>match</key>
        <string>([a-zA-Z_]\w*)(&lt;[a-zA-Z_]\w*&gt;)?(?=\()</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#builtin</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\w*</string>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage_types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#custom_type</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Floating-point literals</string>
        <key>match</key>
        <string>(\.\d+([Ee][-+]\d+)?i?)\b|\b\d+\.\d*(([Ee][-+]\d+)?i?\b)?</string>
        <key>name</key>
        <string>constant.numeric.floating-point.fyr</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Integers</string>
        <key>match</key>
        <string>\b((0x[0-9a-fA-F]+)|(0[0-7]+i?)|(\d+([Ee]\d+)?i?)|(\d+[Ee][-+]\d+i?))\b</string>
        <key>name</key>
        <string>constant.numeric.integer.fyr</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Language constants</string>
        <key>match</key>
        <string>\b(true|false|nil|iota)\b</string>
        <key>name</key>
        <string>constant.language.fyr</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Package declarations</string>
        <key>match</key>
        <string>(?&lt;=package)\s+([a-zA-Z_]\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.package.fyr</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Single line import declarations</string>
        <key>match</key>
        <string>(?&lt;=import)(\s+((?!\s+")[^\s]*)?\s*)((")([^"]*)("))</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.alias.import.fyr</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.fyr</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.fyr</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.import.fyr</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.fyr</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Multiline import declarations</string>
        <key>begin</key>
        <string>(?&lt;=import)\s+(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.other.bracket.round.fyr</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((?!\s+")[^\s]*)?\s+((")([^"]*)("))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.alias.import.fyr</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.fyr</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.fyr</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.import.fyr</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.fyr</string>
              </dict>
            </dict>
          </dict>
        </array>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.other.bracket.round.fyr</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Type declarations</string>
        <key>match</key>
        <string>(?&lt;=type)\s+([a-zA-Z_]\w*)(&lt;[a-zA-Z_]\w*&gt;)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.fyr</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage_types</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#custom_type</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Shorthand variable declaration and assignments</string>
        <key>match</key>
        <string>[a-zA-Z_]\w*(?:,\s*[a-zA-Z_]\w*)*(?=\s*:=)</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>[a-zA-Z_]\w*</string>
                <key>name</key>
                <string>variable.other.assignment.fyr</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#delimiters</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Assignments to existing variables</string>
        <key>match</key>
        <string>(?&lt;!var|let)\s*([a-zA-Z_]\w*(?:,\s*[a-zA-Z_]\w*)*)(?=\s*=[^=])</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>[a-zA-Z_]\w*</string>
                <key>name</key>
                <string>variable.other.assignment.fyr</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#delimiters</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Single line variable declarations/assignments</string>
        <key>match</key>
        <string>(?&lt;=var|let)\s+([^"]*|"[^"]+)$</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Multiline variable declarations/assignments</string>
        <key>begin</key>
        <string>(\b(var|let)\b)\s+(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.var.fyr</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.other.bracket.round.fyr</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.other.bracket.round.fyr</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>Type casting</string>
        <key>match</key>
        <string>&lt;(#[a-z]*\s)?([a-z0-9]*)&gt;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#keywords</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#storage_types</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Terminators</string>
        <key>match</key>
        <string>;</string>
        <key>name</key>
        <string>punctuation.terminator.fyr</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#brackets</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#delimiters</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#runes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#storage_types</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Variable usages</string>
        <key>match</key>
        <string>\b([a-zA-Z_]\w*)\b</string>
        <key>name</key>
        <string>variable.other.fyr</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\{|\}</string>
            <key>name</key>
            <string>punctuation.other.bracket.curly.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\(|\)</string>
            <key>name</key>
            <string>punctuation.other.bracket.round.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\[|\]</string>
            <key>name</key>
            <string>punctuation.other.bracket.square.fyr</string>
          </dict>
        </array>
      </dict>
      <key>delimiters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.other.comma.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.(?!\.\.)</string>
            <key>name</key>
            <string>punctuation.other.period.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>:(?!=)</string>
            <key>name</key>
            <string>punctuation.other.colon.fyr</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>Flow control keywords</string>
            <key>match</key>
            <string>\b(break|continue|else|for|if|in|return)\b</string>
            <key>name</key>
            <string>keyword.control.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(async|spawn|yield|component)\b</string>
            <key>name</key>
            <string>keyword.execution.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(export|extends|func|import|is|package)\b</string>
            <key>name</key>
            <string>keyword.meta.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(const|map|struct|this|type|var|let)\b</string>
            <key>name</key>
            <string>keyword.data.fyr</string>
          </dict>
        </array>
      </dict>
      <key>builtin</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(append|cap|clone|copy|len|make|move|new|panic|push|println|print|real|recover|slice|take|tryPush)\b</string>
            <key>name</key>
            <string>support.function.builtin.fyr</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>comment</key>
        <string>Note that the order here is very important!</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\*|&amp;)(?=\w)</string>
            <key>name</key>
            <string>keyword.operator.address.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\-\-</string>
            <key>name</key>
            <string>keyword.operator.decrement.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\+\+</string>
            <key>name</key>
            <string>keyword.operator.increment.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&lt;&lt;|&gt;&gt;)</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.bitwise.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
            <key>name</key>
            <string>keyword.operator.comparison.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&amp;&amp;|\|\||!)</string>
            <key>name</key>
            <string>keyword.operator.logical.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=|\+=|\-=|\|=|\^=|\*=|/=|:=|%=|&lt;&lt;=|&gt;&gt;=|&amp;\^=|&amp;=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\+|\-|\*|/|%)</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&amp;(?!\^)|\||\^|&amp;\^)</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.bitwise.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.\.</string>
            <key>name</key>
            <string>keyword.operator.ellipsis.fyr</string>
          </dict>
        </array>
      </dict>
      <key>runes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\'(\\([0-7]{3}|[abfnrtv\\'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8})|\p{Any})\'</string>
            <key>name</key>
            <string>constant.other.rune.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\'.*\'</string>
            <key>name</key>
            <string>invalid.illegal.unknown-rune.fyr</string>
          </dict>
        </array>
      </dict>
      <key>storage_types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bbool\b</string>
            <key>name</key>
            <string>storage.type.boolean.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bbyte\b</string>
            <key>name</key>
            <string>storage.type.byte.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\berror\b</string>
            <key>name</key>
            <string>storage.type.error.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(double|float|u?int(8|16|32|64)?)\b</string>
            <key>name</key>
            <string>storage.type.numeric.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\brune\b</string>
            <key>name</key>
            <string>storage.type.rune.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bchar\b</string>
            <key>name</key>
            <string>storage.type.char.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bstring\b</string>
            <key>name</key>
            <string>storage.type.string.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bcoroutine\b</string>
            <key>name</key>
            <string>storage.type.coroutine.fyr</string>
          </dict>
        </array>
      </dict>
      <key>custom_type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[A-Z]\w*\b</string>
            <key>name</key>
            <string>entity.name.type.fyr</string>
          </dict>
        </array>
      </dict>
      <key>string_escaped_char</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\([0-7]{3}|[abfnrtv\\'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8})</string>
            <key>name</key>
            <string>constant.character.escape.fyr</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[^0-7xuUabfnrtv\'"]</string>
            <key>name</key>
            <string>invalid.illegal.unknown-escape.fyr</string>
          </dict>
        </array>
      </dict>
      <key>string_placeholder</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>%(\[\d+\])?([\+#\-0\x20]{,2}((\d+|\*)?(\.?(\d+|\*|(\[\d+\])\*?)?(\[\d+\])?)?))?[vT%tbcdoqxXUbeEfFgGsp]</string>
            <key>name</key>
            <string>constant.other.placeholder.fyr</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>comment</key>
        <string>First add tests and make sure existing tests still pass when changing anything here!</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>variable assignments without type</string>
            <key>match</key>
            <string>([a-zA-Z_]\w*(?:,\s*[a-zA-Z_]\w*)*)\s*=(.*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>[a-zA-Z_]\w*</string>
                    <key>name</key>
                    <string>variable.other.assignment.fyr</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#delimiters</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>variable assignments with type declaration</string>
            <key>match</key>
            <string>([a-zA-Z_]\w*(?:,\s*[a-zA-Z_]\w*)*)(\s+[^=,]*\s*)?=(.*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>[a-zA-Z_]\w*</string>
                    <key>name</key>
                    <string>variable.other.assignment.fyr</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#delimiters</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type_declaration</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>([a-zA-Z_]\w*(?:,\s*[a-zA-Z_]\w*)*)(\s+[^=,]*\s*)?([^=].*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>[a-zA-Z_]\w*</string>
                    <key>name</key>
                    <string>variable.other.declaration.fyr</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#delimiters</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type_declaration</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>type_declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[\*~\^]?(\[.*\])?(\w+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>$self</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#storage_types</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#custom_type</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
    <key>version</key>
    <string>0.1.0</string>
  </dict>
</plist>